/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IfmStories {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIfmStoriesElement extends Components.IfmStories, HTMLStencilElement {
    }
    var HTMLIfmStoriesElement: {
        prototype: HTMLIfmStoriesElement;
        new (): HTMLIfmStoriesElement;
    };
    interface HTMLElementTagNameMap {
        "ifm-stories": HTMLIfmStoriesElement;
    }
}
declare namespace LocalJSX {
    interface IfmStories {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ifm-stories": IfmStories;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ifm-stories": LocalJSX.IfmStories & JSXBase.HTMLAttributes<HTMLIfmStoriesElement>;
        }
    }
}
